logging: True
verbose: 1
debug: False
logdir: "./AgentOccam-Trajectories"
logname: "AgentOccam"
max_steps: 25
agent:
  type: "AgentOccam"
  others:
    max_steps: 25
    logname: "AgentOccam"
    logging: True
    verbose: 1
    debug: False
  actor:
    debug: 0
    verbose: 1
    number: 1
    model: "Qwen2.5-7B-Instruct"
    documented_interaction_elements: ["url", "plan", "reason", "observation summary",
      "retained element ids", "observation highlight"]
    online_interaction_elements: ["tabs"]
    input: ["step", "objective", "previous plans", "interaction history", "current\
        \ observation", "url", "tabs", "retrieved memory"]
    interaction_history:
      verbose: True
      type: ["text"]
      step_num: 3
    current_observation:
      type: ["text"]
    retrieved_memory:
      type: ["text"]
    output: ["interaction history summary", "observation description", "reason", "action",
      "observation highlight"]
    planning_command: ["branch", "prune"]
    navigation_command: ["click", "type", "stop", "note", "go_back"]
    play: ["step", "objective", "previous plans", "observation description", "reason",
      "action"]
    trash: ["objective", "step", "url", "instruction", "online input", "response"]
  critic:
    mode: False
    debug: 0
    verbose: 1
    model: "Qwen2.5-7B-Instruct"
    documented_interaction_elements: []
    online_interaction_elements: ["tabs"]
    character: "normal"
    input: ["objective", "previous plans", "interaction history", "step", "current\
        \ observation", "url", "tabs"]
    interaction_history:
      verbose: True
      type: ["text"]
      step_num: "all"
    current_observation:
      type: ["text"]
    output: ["observation description", "mistakes"]
    trash: ["instruction", "online input", "response"]
  judge:
    mode: True
    debug: 0
    verbose: 1
    model: "Qwen2.5-7B-Instruct"
    documented_interaction_elements: []
    online_interaction_elements: ["tabs"]
    strict: False
    input: ["objective", "previous plans", "interaction history", "step", "current\
        \ observation", "url", "tabs", "action choices"]
    interaction_history:
      verbose: True
      type: ["text"]
      step_num: "all"
    current_observation:
      type: ["text"]
    output: ["plan progress assessment", "action assessment", "action selection"]
    trash: ["instruction", "online input", "response"]
env:
  fullpage: True
  prune: True
  max_browser_rows: 500
  headless: True
  task_ids: [28, 29, 30, 31, 67, 68, 69, 400, 401, 402, 403, 404, 405, 407, 408, 409,
    580, 582, 583, 584, 595, 597, 598, 599, 601, 602, 603, 604, 605, 606, 607, 608,
    611, 612, 613, 614, 615, 616, 617, 618, 620, 621, 622, 624, 626, 627, 628, 629,
    631, 632, 633, 634, 636, 637, 638, 639, 640, 642, 643, 644, 645, 647, 648, 649,
    650, 651, 652, 714, 715, 716, 717, 719, 721, 722, 723, 724, 725, 726, 727, 728,
    729, 731, 732, 733, 734]
